tasks:
  - init: |
      pip install pip-tools
      pip install -r requirements.txt
    command: echo 'start script'
github:
  prebuilds:
    addCheck: prevent-merge-on-error
    addComment: true
ports:
  - port: 8000
    onOpen: open-preview